# Generated by Django 3.1.4 on 2020-12-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.SmallIntegerField(choices=[(0, '技术类'), (1, '产品类'), (2, '运营类'), (3, '设计类')], verbose_name='职位类别')),
                ('job_name', models.CharField(max_length=250, verbose_name='职位名称')),
                ('job_city', models.SmallIntegerField(choices=[(0, '北京'), (1, '上海'), (2, '深圳'), (3, '西安')], verbose_name='工作地点')),
                ('job_responsibility', models.TextField(max_length=1024, verbose_name='职位职责')),
                ('job_requirement', models.TextField(max_length=1024, verbose_name='职位要求')),
                ('creator', models.CharField(max_length=200, verbose_name='创建人')),
                ('created_date', models.DateTimeField(verbose_name='创建时间')),
                ('modified_date', models.DateTimeField(verbose_name='修改时间')),
            ],
        ),
    ]
