# Generated by Django 3.1.3 on 2020-12-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': '职位', 'verbose_name_plural': '职位列表'},
        ),
    ]
