# Generated by Django 3.1.3 on 2020-12-10 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_auto_20201209_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'permissions': [('export', 'Can export candidate list.'), ('notify', 'notify interviewer for candidate review.')], 'verbose_name': '应聘者', 'verbose_name_plural': '应聘者'},
        ),
    ]
